[package]
name = "skill-capture-backend"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["secrets", "tls", "json", "uuid"] }
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"
